spring:
  application:
    name: notificationService
  data:
    mongodb:
      uri : mongodb+srv://tprabu:Master#123@digitalwallet.n7tu1qc.mongodb.net/?retryWrites=true&w=majority
      database: digitalwallet
      port: 27017

logging:
  level:
    org:
      springframework:
        web: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
server:
  port: 8080